LabPpw2017/LabPpw2017/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, delete_friend, friend_list_json, friend_list

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add-friend/$', add_friend, name='add-friend'),
	url(r'^validate-npm/$', validate_npm, name='validate-npm'),
	url(r'^delete-friend/$', delete_friend, name='delete-friend'),
	url(r'^get-friend-list/$', friend_list_json, name='get-friend-list'),
	url(r'^friend-list/$', friend_list, name='friend-list')
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
from lab_1.views import index as index_lab1
import lab_2_addon.urls as lab_2_addon
from django.views.generic import RedirectView
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
	url(r'^lab-2-addon/', include(lab_2_addon,namespace= 'lab-2-addon')),
	url(r'^$', RedirectView.as_view(url='lab-8/', permanent=True), name='index'),
	url(r'^lab-3/', include(lab_3,namespace='lab-3')),
	url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10')),
]

lab_7/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Friend(models.Model):
	friend_name = models.CharField(max_length=400)
	npm = models.CharField(max_length=250, unique=True)
	added_at = models.DateField(auto_now_add=True)

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseBadRequest
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers

from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import json

response = {}

def index(request):
	page = request.GET.get('page', 1)
	csui_helper = CSUIhelper()
	mahasiswa_list, has_prev, has_next = csui_helper.instance.get_mahasiswa_list(page)

	friend_list = Friend.objects.all()
	response = {"mahasiswa_list": mahasiswa_list,
				"friend_list": friend_list,
				"has_prev" : has_prev,
				"has_next" : has_next,
				"page" : page}
	html = 'lab_7/lab_7.html'
	return render(request, html, response)


def friend_list(request):
	html = 'lab_7/daftar_teman.html'
	return render(request, html, response)


@csrf_exempt
def add_friend(request):
	if request.method == 'POST':
		name = request.POST.get('name', None)
		npm = request.POST.get('npm', None)
		if name is None or npm is None or npm_exists_in_friend(npm):
			return HttpResponseBadRequest()

		friend = Friend(friend_name=name, npm=npm)
		friend.save()
		data = model_to_dict(friend)
		return HttpResponse(data)
	return HttpResponseBadRequest()


@csrf_exempt
def delete_friend(request):
	if request.method == 'POST':
		friend_id = request.POST.get('id', None)
		if friend_id is None:
			return HttpResponseBadRequest()

		Friend.objects.filter(id=friend_id).delete()
		return HttpResponse()
	return HttpResponseBadRequest()


@csrf_exempt
def friend_list_json(request):
	friends = Friend.objects.all()
	data = [{'id': friend.id, 'friend_name': friend.friend_name, 'npm': friend.npm} for friend in friends]
	return HttpResponse(json.dumps(data))


@csrf_exempt
def validate_npm(request):
	npm = request.POST.get('npm', None)
	if npm is None:
		return HttpResponseBadRequest()
	data = {'is_taken': npm_exists_in_friend(npm)}
	return JsonResponse(data)


def npm_exists_in_friend(npm):
	return False if not npm else Friend.objects.filter(npm=npm).exists()


def model_to_dict(obj):
	data = serializers.serialize('json', [obj,])
	struct = json.loads(data)
	data = json.dumps(struct[0]["fields"])
	return data

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
	<section name="friend-list">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-lg-8">
					<h2> Teman Fasilkom</h2>
					<div id="friend-list" class="list-group">

					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}
{% block javascript %}
	<script>

		var deleteFriend = function(id) {
			$.ajax({
				method: "POST",
				url:'{% url "lab-7:delete-friend" %}',
				data: {
					id: id
				},
				success: function(data) {
					$('#friend-' + id).remove();
				},
				error: function(error) {
					alert("Terdapat kesalahan pada server, mohon mencoba beberapa saat lagi");
				}
			});
		};

		$( document ).ready(function () {
			$.ajax({
				method: "GET",
				url:'{% url "lab-7:get-friend-list" %}',
				success: function (response) {
					friends = $.parseJSON(response);
					for (var i=0;i<friends.length;i++)
					{
						friend = friends[i];
						$('#friend-list').append(
							'<a class="list-group-item clearfix" id="friend-' + friend.id + '">' +
								friend.friend_name + " (" + friend.npm + ")" +
								'<span class="pull-right">' +
									'<span class="btn btn-xs btn-default" onClick="deleteFriend(' + friend.id + ')">' +
										'Hapus teman' +
									'</span>' +
								'</span>' +
							'</a>'
						);
					}
				},
				error: function(error){
					alert("Terdapat kesalahan pada server, mohon coba beberapa saat lagi.");
				}
			});
		});
	</script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
 <div class="container">
	 <div class="row">
		 <div class="col-md-8 col-lg-8">
			 <h2>Mahasiswa Fasilkom</h2>
			 <div class="list-group">
				 {% if mahasiswa_list %}
					 {% for mahasiswa in mahasiswa_list %}
						 <a class="list-group-item clearfix">
							 {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
							 <span class="pull-right">
								 <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
									 Tambah sebagai teman
								 </span>
							 </span>
						 </a>
					 {% endfor %}
					<ul class="pager">
						{% if has_prev %} <li><a href="?page={{ page|add:'-1' }}">Sebelumnya</a></li> {% endif %}
						{% if has_next %} <li><a href="?page={{ page|add:'1' }}">Berikutnya</a></li> {% endif %}
					</ul>
				 {% else %}
					 <div class="alert alert-danger text-center">
						 <strong>Oops!</strong> Tidak ada mahasiswa
					 </div>
				 {% endif %}
			 </div>
		 </div>
		 <div class="col-lg-4">
			 <h2>Teman Saya</h2>

			 <div class="list-group" id="friend-list">
				 {% if friend_list %}
					 {% for friend in friend_list %}
						 <a class="list-group-item clearfix">
							 {{ friend.friend_name }} ({{ friend.npm }})
						 </a>
					 {% endfor %}
				 {% else %}
					 <div id="nofriend" class="alert alert-danger text-center">
						 <strong>Oops!</strong> Tidak ada teman
					 </div>
				 {% endif %}
			 </div>
			 <form id="add-friend" action="#">
				 {% csrf_token %}
				 <label for="field_npm">npm</label>
				 <input id="field_npm" required type="number" name="npm" class="form-control"/>
				 <label for="field_name">name</label>
				 <input id="field_name" required  type="text" name="name" class="form-control"/>
				 <button type="submit">Tambah</button>
			 </form>
		 </div>
	 </div>
 </div>
</section>
{% endblock %}

{% block javascript %}
<script>
	var addFriend = function(nama, npm) {
		$.ajax({
			method: "POST",
			url: '{% url "lab-7:add-friend" %}',
			data: {
				name: nama,
				npm: npm
			},
			success : function (friend) {
				friend = $.parseJSON(friend);
				html = '<a class="list-group-item clearfix">' +
							friend.friend_name + " (" + friend.npm + ")" +
						'</a>';
				$("#friend-list").append(html);
				$("#nofriend").hide();
			},
			error : function (error) {
				alert("Mahasiswa dengan NPM tersebut sudah ditambahkan sebagai teman")
			}
		});
	};

	$("#add-friend").on("submit", function () {
		name = $("#field_name").val();
		npm = $("#field_npm").val();
		addFriend(name, npm);
		event.preventDefault();
	});

	$("#field_npm").change(function () {
		console.log( $(this).val() );
		npm = $(this).val();
		$.ajax({
			method: "POST",
			url: '{% url "lab-7:validate-npm" %}',
			data: {
				'npm': npm
			},
			dataType: 'json',
			success: function (data) {
				console.log(data);
				if (data.is_taken) {
					alert("Mahasiswa dengan NPM seperti ini sudah ada");
				}
			}
		});
	});
</script>
{% endblock %}